### ISSUE TITLE
ConfigIniEnv error

### ISSUE THREAD

**Issue by jonanathan** [mozilla/ssm-acquire#12]
I am able to install ssm_acquire successfully on an EC2 Ubuntu 18.04 instance. However, when I try to initialize ssm_acquire, it fails with:
`Traceback (most recent call last):
  File "/usr/local/bin/ssm_acquire", line 7, in <module>
    from ssm_acquire.cli import main
  File "/usr/local/lib/python3.6/dist-packages/ssm_acquire/__init__.py", line 9, in <module>
    from ssm_acquire import analyze
  File "/usr/local/lib/python3.6/dist-packages/ssm_acquire/analyze.py", line 8, in <module>
    from ssm_acquire import common
  File "/usr/local/lib/python3.6/dist-packages/ssm_acquire/common.py", line 4, in <module>
    from everett.manager import ConfigIniEnv
ImportError: cannot import name 'ConfigIniEnv'`

I configured a **.threatresponse.ini** file in /home/ssm-user directory and in my etc folder since I looked at what the ConfigIniEnv function referencing. 

The **.threatresponse.ini** file has the following:
[ssm_acquire]
mfa_serial_number=arn:aws:iam::1234567890:mfa/defaultmfa
asset_bucket=s3_bucket_name
ssm_acquire_role_arn=arn:aws:iam::1234567890:role/defaultrole

Ideally, I wanted to get rid of the MFA parameter as well. But was trying to get this module working as-is.

**Comment by hackersifu** [comment]
That error is related to the ConfigIniEnv file being moved. Within the code, the common.py is referring to this:

from everett.manager import ConfigIniEnv

It need's to be changed to this:

from everett.ext.inifile import ConfigIniEnv

I used the project page as reference: https://pypi.org/project/everett/

**Comment by jonanathan** [comment]
@andrewkrug the common.py file needs to be updated per @hackersifu. Once making that change this issue was resolved.
